export default function App() {
  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <div className="ui-page trait-community trait-playful trait-bold" data-style="discord">
      <header id="top" className="ui-section ui-navigation theme-light variant-global-frosted"><div className="ui-container nav-inner"><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"></span>Campfire</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a className="button primary compact" href="#begin">Create something</a></div></header>
      <main id="main">
      <section id="overview" className="ui-section ui-hero theme-light variant-centered-product"><div className="hero-ambient" aria-hidden="true"></div><div className="ui-container hero-copy"><p className="eyebrow">Campfire</p><h1>Your people, all in one place.</h1><p className="lead">A lively home for communities to talk, create, play, and keep their shared culture close.</p><div className="actions"><a className="button primary" href="#experience">Create something</a><a className="button secondary" href="#principles">See the story</a></div></div><figure className="hero-visual"><div className="visual-frame"><img src="/ui/discord/discord-composition.svg" alt="Original abstract composition representing the Campfire experience" width="1600" height="900" /></div></figure></section>
      <section id="community" className="ui-section ui-logo-cloud theme-light variant-ticker"><div className="ui-container"><h2>Trusted by teams building with Campfire.</h2><ul className="logo-row"><li>Northstar</li><li>Common Ground</li><li>Bright Labs</li><li>Open Field</li><li>New Arc</li><li>Good Work</li></ul></div></section>
      <section id="principles" className="ui-section ui-features theme-light variant-bento"><div className="ui-container"><p className="eyebrow">Guiding principles</p><h2>What makes Campfire feel different.</h2><p className="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div className="feature-grid"><article><div className="feature-top"><span className="marker">01</span><span className="feature-line" aria-hidden="true"></span></div><h3>Easy to enter</h3><p>Campfire presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><div className="feature-top"><span className="marker">02</span><span className="feature-line" aria-hidden="true"></span></div><h3>Flexible by nature</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><div className="feature-top"><span className="marker">03</span><span className="feature-line" aria-hidden="true"></span></div><h3>Delight in the details</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
      <section id="experience" className="ui-section ui-showcase theme-dark variant-split"><div className="ui-container showcase-grid"><div><p className="eyebrow">The experience</p><h2>Serious capability, joyful by default.</h2><p className="lead">Campfire brings its most important ideas forward and lets every supporting detail recede.</p><a className="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/discord/discord-composition.svg" alt="Original abstract composition representing the Campfire experience" width="1600" height="900" loading="lazy" /></figure></div></section>
      <section id="voices" className="ui-section ui-testimonials theme-light variant-cards"><div className="ui-container"><h2>What people notice about Campfire.</h2><div className="quote-grid"><figure><blockquote>The experience feels considered from the first moment, but never asks us to learn its logic.</blockquote><figcaption>Mara Chen · Design lead</figcaption></figure><figure><blockquote>We moved faster without sacrificing the quality or clarity our customers expect.</blockquote><figcaption>Jon Bell · Product director</figcaption></figure><figure><blockquote>It gives the team enough structure to stay aligned and enough room to do original work.</blockquote><figcaption>Amara Okafor · Studio founder</figcaption></figure></div></div></section>
      <section id="begin" className="ui-section ui-cta theme-light variant-centered"><div className="ui-container cta-shell"><div className="cta-inner"><p className="eyebrow">The next step</p><h2>Make the next idea feel possible.</h2><p className="lead">Discover how Campfire can turn a clear idea into an experience people remember.</p><a className="button primary" href="#top">Create something</a></div></div></section>
      </main>
      <footer id="footer" className="ui-section ui-footer theme-light variant-minimal"><div className="ui-container footer-grid"><div><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"></span>Campfire</a><p>A lively home for communities to talk, create, play, and keep their shared culture close.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p className="ui-container legal">© 2026 Campfire. An original Praxis Flow demonstration brand.</p></footer>
      </div>
    </>
  );
}
