export default function Home() {
  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <header id="top" className="ui-section ui-navigation theme-dark variant-global"><div className="ui-container nav-inner"><a className="brand" href="#top">Northline</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a className="button primary compact" href="#begin">Discover the collection</a></div></header>
      <main id="main">
      <section id="overview" className="ui-section ui-hero theme-light variant-immersive"><div className="ui-container hero-copy"><p className="eyebrow">Northline</p><h1>The road, reconsidered.</h1><p className="lead">A refined mobility concept that pairs quiet power with deliberate everyday comfort.</p><div className="actions"><a className="button primary" href="#experience">Discover the collection</a><a className="button secondary" href="#principles">See the story</a></div></div><figure className="hero-visual"><img src="/ui/bmw/bmw-composition.svg" alt="Original abstract composition representing the Northline experience" width="1600" height="900" /></figure></section>
      <section id="experience" className="ui-section ui-showcase theme-light variant-full-bleed"><div className="ui-container showcase-grid"><div><p className="eyebrow">The experience</p><h2>Crafted around a singular feeling.</h2><p className="lead">Northline brings its most important ideas forward and lets every supporting detail recede.</p><a className="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/bmw/bmw-composition.svg" alt="Original abstract composition representing the Northline experience" width="1600" height="900" loading="lazy" /></figure></div></section>
      <section id="craft" className="ui-section ui-showcase theme-light variant-light-stage"><div className="ui-container showcase-grid"><div><p className="eyebrow">The craft</p><h2>Material, light, and motion in balance.</h2><p className="lead">Purposeful materials, durable choices, and a precise visual rhythm make the experience feel complete without feeling crowded.</p><a className="text-link" href="#principles">Read the principles</a></div><div className="material-study" aria-hidden="true"><span></span><span></span><span></span></div></div></section>
      <section id="principles" className="ui-section ui-features theme-light variant-alternating"><div className="ui-container"><p className="eyebrow">Guiding principles</p><h2>What makes Northline feel different.</h2><p className="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div className="feature-grid"><article><span className="marker">01</span><h3>Sculpted proportion</h3><p>Northline presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><span className="marker">02</span><h3>Purposeful material</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><span className="marker">03</span><h3>Measured performance</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
      <section id="proof" className="ui-section ui-metrics theme-dark variant-inline"><div className="ui-container"><p className="eyebrow">Measured in practice</p><h2>Northline, by the numbers.</h2><dl className="metrics-grid"><div><dt>less wasted effort</dt><dd>42%</dd></div><div><dt>customer delight</dt><dd>8.7/10</dd></div><div><dt>ready when needed</dt><dd>24/7</dd></div></dl></div></section>
      <section id="begin" className="ui-section ui-cta theme-dark variant-centered"><div className="ui-container cta-inner"><p className="eyebrow">The next step</p><h2>Experience the work in its purest form.</h2><p className="lead">Discover how Northline can turn a clear idea into an experience people remember.</p><a className="button primary" href="#top">Discover the collection</a></div></section>
      </main>
      <footer id="footer" className="ui-section ui-footer theme-light variant-minimal"><div className="ui-container footer-grid"><div><a className="brand" href="#top">Northline</a><p>A refined mobility concept that pairs quiet power with deliberate everyday comfort.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p className="ui-container legal">© 2026 Northline. An original Praxis Flow demonstration brand.</p></footer>
    </>
  );
}
