export default function App() {
  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <div className="ui-page trait-finance trait-clean trait-trustworthy" data-style="coinbase">
      <header id="top" className="ui-section ui-navigation theme-dark variant-global"><div className="ui-container nav-inner"><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"></span>Harbor</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a className="button primary compact" href="#begin">Start building</a></div></header>
      <main id="main">
      <section id="overview" className="ui-section ui-hero theme-light variant-centered-product"><div className="hero-ambient" aria-hidden="true"></div><div className="ui-container hero-copy"><p className="eyebrow">Harbor</p><h1>A clearer way into digital finance.</h1><p className="lead">Secure tools and plain-language guidance for holding, moving, and understanding value.</p><div className="actions"><a className="button primary" href="#experience">Start building</a><a className="button secondary" href="#principles">See the story</a></div></div><figure className="hero-visual"><div className="visual-frame"><img src="/ui/coinbase/coinbase-composition.svg" alt="Original abstract composition representing the Harbor experience" width="1600" height="900" /></div></figure></section>
      <section id="proof" className="ui-section ui-metrics theme-dark variant-grid"><div className="ui-container"><p className="eyebrow">Measured in practice</p><h2>Harbor, by the numbers.</h2><dl className="metrics-grid"><div><dt>typical response</dt><dd>18 ms</dd></div><div><dt>service availability</dt><dd>99.99%</dd></div><div><dt>faster iteration</dt><dd>3×</dd></div></dl></div></section>
      <section id="principles" className="ui-section ui-features theme-light variant-grid"><div className="ui-container"><p className="eyebrow">Guiding principles</p><h2>What makes Harbor feel different.</h2><p className="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div className="feature-grid"><article><div className="feature-top"><span className="marker">01</span><span className="feature-line" aria-hidden="true"></span></div><h3>Observable by default</h3><p>Harbor presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><div className="feature-top"><span className="marker">02</span><span className="feature-line" aria-hidden="true"></span></div><h3>Fast under pressure</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><div className="feature-top"><span className="marker">03</span><span className="feature-line" aria-hidden="true"></span></div><h3>Open at the edges</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
      <section id="experience" className="ui-section ui-showcase theme-light variant-split"><div className="ui-container showcase-grid"><div><p className="eyebrow">The experience</p><h2>Clarity at every layer.</h2><p className="lead">Harbor brings its most important ideas forward and lets every supporting detail recede.</p><a className="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/coinbase/coinbase-composition.svg" alt="Original abstract composition representing the Harbor experience" width="1600" height="900" loading="lazy" /></figure></div></section>
      <section id="community" className="ui-section ui-logo-cloud theme-light variant-row"><div className="ui-container"><h2>Trusted by teams building with Harbor.</h2><ul className="logo-row"><li>Northstar</li><li>Common Ground</li><li>Bright Labs</li><li>Open Field</li><li>New Arc</li><li>Good Work</li></ul></div></section>
      <section id="begin" className="ui-section ui-cta theme-light variant-band"><div className="ui-container cta-shell"><div className="cta-inner"><p className="eyebrow">The next step</p><h2>Put clarity into production.</h2><p className="lead">Discover how Harbor can turn a clear idea into an experience people remember.</p><a className="button primary" href="#top">Start building</a></div></div></section>
      </main>
      <footer id="footer" className="ui-section ui-footer theme-light variant-columns"><div className="ui-container footer-grid"><div><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"></span>Harbor</a><p>Secure tools and plain-language guidance for holding, moving, and understanding value.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p className="ui-container legal">© 2026 Harbor. An original Praxis Flow demonstration brand.</p></footer>
      </div>
    </>
  );
}
