<script setup>
</script>

<template>
  <a class="skip-link" href="#main">Skip to content</a>
  <div class="ui-page trait-ai trait-soft trait-playful" data-style="lovable">
  <header id="top" class="ui-section ui-navigation theme-light variant-global-frosted"><div class="ui-container nav-inner"><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true"></span>Bloomlab</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a class="button primary compact" href="#begin">Create something</a></div></header>
  <main id="main">
  <section id="overview" class="ui-section ui-hero theme-light variant-centered-product"><div class="hero-ambient" aria-hidden="true"></div><div class="ui-container hero-copy"><p class="eyebrow">Bloomlab</p><h1>Turn an idea into something people can use.</h1><p class="lead">A friendly building space that helps small teams move from a sentence to a polished product.</p><div class="actions"><a class="button primary" href="#experience">Create something</a><a class="button secondary" href="#principles">See the story</a></div></div><figure class="hero-visual"><div class="visual-frame"><img src="/ui/lovable/lovable-composition.svg" alt="Original abstract composition representing the Bloomlab experience" width="1600" height="900" /></div></figure></section>
  <section id="community" class="ui-section ui-logo-cloud theme-light variant-ticker"><div class="ui-container"><h2>Trusted by teams building with Bloomlab.</h2><ul class="logo-row"><li>Northstar</li><li>Common Ground</li><li>Bright Labs</li><li>Open Field</li><li>New Arc</li><li>Good Work</li></ul></div></section>
  <section id="principles" class="ui-section ui-features theme-light variant-bento"><div class="ui-container"><p class="eyebrow">Guiding principles</p><h2>What makes Bloomlab feel different.</h2><p class="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div class="feature-grid"><article><div class="feature-top"><span class="marker">01</span><span class="feature-line" aria-hidden="true"></span></div><h3>Easy to enter</h3><p>Bloomlab presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><div class="feature-top"><span class="marker">02</span><span class="feature-line" aria-hidden="true"></span></div><h3>Flexible by nature</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><div class="feature-top"><span class="marker">03</span><span class="feature-line" aria-hidden="true"></span></div><h3>Delight in the details</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
  <section id="experience" class="ui-section ui-showcase theme-light variant-split"><div class="ui-container showcase-grid"><div><p class="eyebrow">The experience</p><h2>Serious capability, joyful by default.</h2><p class="lead">Bloomlab brings its most important ideas forward and lets every supporting detail recede.</p><a class="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/lovable/lovable-composition.svg" alt="Original abstract composition representing the Bloomlab experience" width="1600" height="900" loading="lazy" /></figure></div></section>
  <section id="voices" class="ui-section ui-testimonials theme-light variant-cards"><div class="ui-container"><h2>What people notice about Bloomlab.</h2><div class="quote-grid"><figure><blockquote>The experience feels considered from the first moment, but never asks us to learn its logic.</blockquote><figcaption>Mara Chen · Design lead</figcaption></figure><figure><blockquote>We moved faster without sacrificing the quality or clarity our customers expect.</blockquote><figcaption>Jon Bell · Product director</figcaption></figure><figure><blockquote>It gives the team enough structure to stay aligned and enough room to do original work.</blockquote><figcaption>Amara Okafor · Studio founder</figcaption></figure></div></div></section>
  <section id="begin" class="ui-section ui-cta theme-light variant-centered"><div class="ui-container cta-shell"><div class="cta-inner"><p class="eyebrow">The next step</p><h2>Make the next idea feel possible.</h2><p class="lead">Discover how Bloomlab can turn a clear idea into an experience people remember.</p><a class="button primary" href="#top">Create something</a></div></div></section>
  </main>
  <footer id="footer" class="ui-section ui-footer theme-light variant-minimal"><div class="ui-container footer-grid"><div><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true"></span>Bloomlab</a><p>A friendly building space that helps small teams move from a sentence to a polished product.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p class="ui-container legal">© 2026 Bloomlab. An original Praxis Flow demonstration brand.</p></footer>
  </div>
</template>
