export default function Home() {
  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <div className="ui-page trait-productivity trait-minimal trait-editorial" data-style="notion">
      <header id="top" className="ui-section ui-navigation theme-light variant-editorial"><div className="ui-container nav-inner"><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"></span>Papertrail</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a className="button primary compact" href="#begin">Explore the story</a></div></header>
      <main id="main">
      <section id="overview" className="ui-section ui-hero theme-light variant-split-editorial"><div className="hero-ambient" aria-hidden="true"></div><div className="ui-container hero-copy"><p className="eyebrow">Papertrail</p><h1>A quieter place for everything you know.</h1><p className="lead">Documents, projects, and team memory arranged in one calm, adaptable workspace.</p><div className="actions"><a className="button primary" href="#experience">Explore the story</a><a className="button secondary" href="#principles">See the story</a></div></div><figure className="hero-visual"><div className="visual-frame"><img src="/ui/notion/notion-composition.svg" alt="Original abstract composition representing the Papertrail experience" width="1600" height="900" /></div></figure></section>
      <section id="experience" className="ui-section ui-showcase theme-light variant-split"><div className="ui-container showcase-grid"><div><p className="eyebrow">The experience</p><h2>Every detail supports the story.</h2><p className="lead">Papertrail brings its most important ideas forward and lets every supporting detail recede.</p><a className="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/notion/notion-composition.svg" alt="Original abstract composition representing the Papertrail experience" width="1600" height="900" loading="lazy" /></figure></div></section>
      <section id="principles" className="ui-section ui-features theme-light variant-alternating"><div className="ui-container"><p className="eyebrow">Guiding principles</p><h2>What makes Papertrail feel different.</h2><p className="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div className="feature-grid"><article><div className="feature-top"><span className="marker">01</span><span className="feature-line" aria-hidden="true"></span></div><h3>Clear from the start</h3><p>Papertrail presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><div className="feature-top"><span className="marker">02</span><span className="feature-line" aria-hidden="true"></span></div><h3>Human at every scale</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><div className="feature-top"><span className="marker">03</span><span className="feature-line" aria-hidden="true"></span></div><h3>Made to endure</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
      <section id="voices" className="ui-section ui-testimonials theme-light variant-editorial"><div className="ui-container"><h2>What people notice about Papertrail.</h2><div className="quote-grid"><figure><blockquote>The experience feels considered from the first moment, but never asks us to learn its logic.</blockquote><figcaption>Mara Chen · Design lead</figcaption></figure><figure><blockquote>We moved faster without sacrificing the quality or clarity our customers expect.</blockquote><figcaption>Jon Bell · Product director</figcaption></figure><figure><blockquote>It gives the team enough structure to stay aligned and enough room to do original work.</blockquote><figcaption>Amara Okafor · Studio founder</figcaption></figure></div></div></section>
      <section id="craft" className="ui-section ui-showcase theme-light variant-light-stage"><div className="ui-container showcase-grid"><div><p className="eyebrow">The craft</p><h2>Designed for the moments between milestones.</h2><p className="lead">Purposeful materials, durable choices, and a precise visual rhythm make the experience feel complete without feeling crowded.</p><a className="text-link" href="#principles">Read the principles</a></div><div className="material-study" aria-hidden="true"><span></span><span></span><span></span></div></div></section>
      <section id="begin" className="ui-section ui-cta theme-light variant-split"><div className="ui-container cta-shell"><div className="cta-inner"><p className="eyebrow">The next step</p><h2>Begin with a more thoughtful experience.</h2><p className="lead">Discover how Papertrail can turn a clear idea into an experience people remember.</p><a className="button primary" href="#top">Explore the story</a></div></div></section>
      </main>
      <footer id="footer" className="ui-section ui-footer theme-light variant-minimal"><div className="ui-container footer-grid"><div><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"></span>Papertrail</a><p>Documents, projects, and team memory arranged in one calm, adaptable workspace.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p className="ui-container legal">© 2026 Papertrail. An original Praxis Flow demonstration brand.</p></footer>
      </div>
    </>
  );
}
