import "./globals.css";

export const metadata = {
  title: "{{projectName}}",
  description: "Generated by Praxis Flow",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en"><body>{children}</body></html>;
}
