export const STYLE_PROFILES = [
  profile("airbnb", "Wayfarer", "Stay somewhere that stays with you.", "A thoughtful travel collection shaped around local character and effortless arrival.", "editorial", "light", ["editorial", "travel", "warm"]),
  profile("airtable", "Fieldnote", "Make every moving part visible.", "A flexible workspace that turns complex projects into a clear, colorful shared rhythm.", "playful", "light", ["colorful", "modular", "playful"]),
  profile("binance", "Meridian Ledger", "Move value with confidence.", "A precise financial platform for seeing markets clearly and acting without friction.", "technical", "dark", ["finance", "technical", "bold"]),
  profile("bmw-m", "Vector M", "Performance, distilled.", "A limited electric grand tourer engineered around balance, response, and a singular line.", "luxury", "dark", ["automotive", "performance", "bold"]),
  profile("bmw", "Northline", "The road, reconsidered.", "A refined mobility concept that pairs quiet power with deliberate everyday comfort.", "luxury", "light", ["automotive", "premium", "structured"]),
  profile("bugatti", "Élan Atelier", "An object in motion. A work at rest.", "A hand-finished performance study where material, proportion, and velocity meet.", "luxury", "dark", ["luxury", "automotive", "dramatic"]),
  profile("cal", "Tempo", "Time that feels like yours.", "A calmer way to shape meetings, protect focus, and keep a team in step.", "technical", "light", ["minimal", "productivity", "calm"]),
  profile("claude", "Hearth", "Thoughtful work starts with a better conversation.", "A warm, clear thinking space for exploring ideas and turning them into useful work.", "editorial", "light", ["editorial", "warm", "human"]),
  profile("clay", "Signalcraft", "Turn good signals into great relationships.", "A creative growth workspace that helps teams research, enrich, and reach the right people.", "playful", "mixed", ["colorful", "saas", "expressive"]),
  profile("clickhouse", "Columnar", "Answers at the speed of curiosity.", "A high-performance analytics engine built for deep questions over enormous live datasets.", "technical", "dark", ["data", "technical", "bold"]),
  profile("coinbase", "Harbor", "A clearer way into digital finance.", "Secure tools and plain-language guidance for holding, moving, and understanding value.", "technical", "light", ["finance", "clean", "trustworthy"]),
  profile("cursor", "Threadline", "Build in the flow of thought.", "An intelligent code workspace that keeps context close and friction out of the way.", "technical", "dark", ["developer", "technical", "dark"]),
  profile("dell-1996", "PixelPort", "The future just dialed in.", "A joyful desktop gateway packed with bright ideas, useful tools, and unmistakable web nostalgia.", "playful", "light", ["retro", "playful", "nostalgic"]),
  profile("discord", "Campfire", "Your people, all in one place.", "A lively home for communities to talk, create, play, and keep their shared culture close.", "playful", "mixed", ["community", "playful", "bold"]),
  profile("elevenlabs", "Resonant", "Give every idea a voice.", "A studio for creating expressive, natural audio across stories, products, and languages.", "editorial", "dark", ["audio", "atmospheric", "premium"]),
  profile("expo", "Relay Mobile", "Ship the moment it works.", "One focused toolkit for building, testing, and delivering ambitious cross-platform experiences.", "technical", "dark", ["developer", "mobile", "technical"]),
  profile("ferrari", "Rosso Works", "Born from the racing line.", "A modern performance atelier translating track discipline into an unforgettable road experience.", "luxury", "mixed", ["automotive", "editorial", "dramatic"]),
  profile("figma", "Patchwork", "Make together, from the first mark.", "A shared creative canvas where teams can explore, prototype, and bring every voice into the work.", "playful", "light", ["creative", "colorful", "collaborative"]),
  profile("framer", "Canvasline", "Publish at the speed of imagination.", "A visual website studio for shaping expressive, responsive experiences without losing momentum.", "playful", "dark", ["creative", "saas", "gradient"]),
  profile("hp", "Brightworks", "Technology made more human.", "Reliable tools designed to help people learn, create, and do their best work anywhere.", "editorial", "light", ["technology", "friendly", "editorial"]),
  profile("lamborghini", "Veloce", "Defy the ordinary line.", "An uncompromising electric performance concept cut from light, sound, and angular motion.", "luxury", "dark", ["automotive", "luxury", "angular"]),
  profile("lovable", "Bloomlab", "Turn an idea into something people can use.", "A friendly building space that helps small teams move from a sentence to a polished product.", "playful", "light", ["ai", "soft", "playful"]),
  profile("mastercard", "Orbit Pay", "A world of moments, moving freely.", "Human-centered payment experiences that connect everyday choices with global possibility.", "editorial", "light", ["finance", "warm", "geometric"]),
  profile("meta", "Commonspace", "Feel closer, wherever you are.", "Open tools for sharing presence, making together, and turning distance into connection.", "playful", "light", ["technology", "social", "gradient"]),
  profile("mongodb", "SproutDB", "Data that grows with the idea.", "A flexible developer data platform built to make the first prototype and the millionth request feel natural.", "technical", "light", ["developer", "data", "editorial"]),
  profile("notion", "Papertrail", "A quieter place for everything you know.", "Documents, projects, and team memory arranged in one calm, adaptable workspace.", "editorial", "light", ["productivity", "minimal", "editorial"]),
  profile("nvidia", "Parallel", "Compute what comes next.", "Accelerated systems for researchers and builders working at the edge of simulation and intelligence.", "technical", "dark", ["technology", "performance", "bold"]),
  profile("ollama", "Localmind", "Intelligence, close to home.", "A simple local runtime that keeps powerful models private, portable, and ready to explore.", "technical", "light", ["developer", "minimal", "calm"]),
  profile("pinterest", "Museboard", "Find the idea behind your next idea.", "A visual place to collect possibilities, follow curiosity, and shape inspiration into a plan.", "editorial", "light", ["visual", "editorial", "discovery"]),
  profile("playstation", "Nightplay", "Enter a world worth staying in.", "A cinematic home for new stories, shared adventures, and unforgettable ways to play.", "luxury", "dark", ["gaming", "cinematic", "bold"]),
  profile("raycast", "Swiftdeck", "Everything you need, one thought away.", "A polished command space that turns daily tools and tiny actions into effortless momentum.", "technical", "dark", ["productivity", "gradient", "premium"]),
  profile("revolut", "Flux Finance", "Money without the old boundaries.", "One modern account for spending, saving, exchanging, and seeing the whole picture clearly.", "editorial", "mixed", ["finance", "bold", "modern"]),
  profile("sentry", "Tracewell", "See the problem before it becomes the story.", "Observability that connects errors, performance, and releases into one useful path to a fix.", "technical", "mixed", ["developer", "observability", "illustrated"]),
  profile("spacex", "Altitude", "Make distance feel possible.", "A mission-driven aerospace program building reusable systems for the next era of exploration.", "luxury", "dark", ["aerospace", "cinematic", "minimal"]),
  profile("supabase", "Openbase", "Build openly. Scale confidently.", "A developer platform pairing a powerful database with the tools every modern product needs.", "technical", "dark", ["developer", "open-source", "technical"]),
  profile("tesla", "Current Motors", "Electric, without compromise.", "A clean-sheet vehicle shaped around range, simplicity, and the pleasure of instant response.", "luxury", "mixed", ["automotive", "minimal", "cinematic"]),
  profile("uber", "Cityline", "Go where the day takes you.", "A direct, dependable way to move through the city, from the first mile to the last.", "editorial", "light", ["urban", "bold", "editorial"]),
  profile("vercel", "Vertex Cloud", "The web, at your pace.", "A precise delivery platform that helps product teams turn code into fast, resilient experiences.", "technical", "mixed", ["developer", "minimal", "geometric"]),
  profile("warp", "Vector Terminal", "The command line, moving with you.", "A modern terminal workspace that brings context, collaboration, and speed to every command.", "technical", "dark", ["developer", "terminal", "gradient"]),
];

function profile(id, brand, hero, body, archetype, theme, traits) {
  return { id, brand, hero, body, archetype, theme, traits };
}
