<script setup lang="ts">
</script>

<template>
  <a class="skip-link" href="#main">Skip to content</a>
  <div class="ui-page trait-minimal trait-premium trait-editorial" data-style="apple">
  <header id="top" class="ui-section ui-navigation theme-dark variant-global-frosted"><div class="ui-container nav-inner"><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true"></span>Stillform</a><nav aria-label="Primary"><ul><li><a href="#studio">Studio</a></li><li><a href="#materials">Materials</a></li><li><a href="#impact">Journal</a></li></ul></nav><a class="button primary compact" href="#reserve">Reserve</a></div></header>
  <main id="main">
  <section id="hero" class="ui-section ui-hero theme-light variant-centered-product"><div class="hero-ambient" aria-hidden="true"></div><div class="ui-container hero-copy"><p class="eyebrow">Stillform One</p><h1>Quietly extraordinary.</h1><p class="lead">A considered collection of everyday objects shaped around calm, clarity, and enduring materials.</p><div class="actions"><a class="button primary" href="#studio">Explore the collection</a><a class="button secondary" href="#impact">Watch the film</a></div></div><figure class="hero-visual"><div class="visual-frame"><img src="/ui/apple/stillform-stage.svg" alt="Three abstract Stillform objects arranged on a quiet display plinth" width="1600" height="900" /></div></figure></section>
  <section id="studio" class="ui-section ui-showcase theme-dark variant-dark-stage"><div class="ui-container showcase-grid"><div><p class="eyebrow">The studio edition</p><h2>Made to disappear into your day.</h2><p class="lead">Balanced proportions, tactile controls, and a surface that changes character with the light.</p><a class="text-link" href="#materials">See every detail</a></div><figure><img src="/ui/apple/stillform-stage.svg" alt="Three abstract Stillform objects arranged on a quiet display plinth" width="1600" height="900" loading="lazy" /></figure></div></section>
  <section id="principles" class="ui-section ui-features theme-light variant-bento"><div class="ui-container"><p class="eyebrow">Designed with restraint</p><h2>Only what earns its place.</h2><p class="lead section-intro">Every decision serves the experience, from the first touch to the thousandth use.</p><div class="feature-grid"><article><div class="feature-top"><span class="marker">01</span><span class="feature-line" aria-hidden="true"></span></div><h3>Tactile by nature</h3><p>Soft-touch controls respond with a precise, reassuring click.</p></article><article><div class="feature-top"><span class="marker">02</span><span class="feature-line" aria-hidden="true"></span></div><h3>Considered materials</h3><p>Recycled aluminum and mineral glass create a durable, quiet finish.</p></article><article><div class="feature-top"><span class="marker">03</span><span class="feature-line" aria-hidden="true"></span></div><h3>Built for repair</h3><p>A modular interior makes essential parts accessible and replaceable.</p></article></div></div></section>
  <section id="materials" class="ui-section ui-showcase theme-light variant-light-stage"><div class="ui-container showcase-grid"><div><p class="eyebrow">Material study</p><h2>Weight you can feel. Impact you cannot.</h2><p class="lead">The enclosure uses reclaimed alloy, refined through a low-energy process and finished without decorative coatings.</p><a class="text-link" href="#impact">Read our material standard</a></div><div class="material-study" aria-hidden="true"><span></span><span></span><span></span></div></div></section>
  <section id="impact" class="ui-section ui-metrics theme-dark variant-inline"><div class="ui-container"><p class="eyebrow">Measured progress</p><h2>Less, by design.</h2><dl class="metrics-grid"><div><dt>recycled enclosure material</dt><dd>74%</dd></div><div><dt>less packaging volume</dt><dd>42%</dd></div><div><dt>repair support commitment</dt><dd>10 yr</dd></div></dl></div></section>
  <section id="reserve" class="ui-section ui-cta theme-light variant-centered"><div class="ui-container cta-shell"><div class="cta-inner"><p class="eyebrow">Available this season</p><h2>Bring calm into focus.</h2><p class="lead">Join the first release and receive a private material sample before your piece is finished.</p><a class="button primary" href="#top">Reserve Stillform One</a></div></div></section>
  </main>
  <footer id="footer" class="ui-section ui-footer theme-light variant-columns"><div class="ui-container footer-grid"><div><a class="brand" href="#top"><span class="brand-mark" aria-hidden="true"></span>Stillform</a><p>Objects for quieter, more intentional days.</p></div><div><h2>Collection</h2><ul><li><a href="#hero">Stillform One</a></li><li><a href="#materials">Materials</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#impact">Journal</a></li><li><a href="#impact">Responsibility</a></li></ul></div></div><p class="ui-container legal">© 2026 Stillform Studio. An original Praxis Flow demonstration brand.</p></footer>
  </div>
</template>
