apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: praxis-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: praxis-cloud-secrets
    kind: ClusterSecretStore
  target:
    name: praxis-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{projectName}}/production
