<script setup>
</script>

<template>
  <a class="skip-link" href="#main">Skip to content</a>
  <header id="top" class="ui-section ui-navigation theme-dark variant-global"><div class="ui-container nav-inner"><a class="brand" href="#top">Current Motors</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a class="button primary compact" href="#begin">Discover the collection</a></div></header>
  <main id="main">
  <section id="overview" class="ui-section ui-hero theme-light variant-immersive"><div class="ui-container hero-copy"><p class="eyebrow">Current Motors</p><h1>Electric, without compromise.</h1><p class="lead">A clean-sheet vehicle shaped around range, simplicity, and the pleasure of instant response.</p><div class="actions"><a class="button primary" href="#experience">Discover the collection</a><a class="button secondary" href="#principles">See the story</a></div></div><figure class="hero-visual"><img src="/ui/tesla/tesla-composition.svg" alt="Original abstract composition representing the Current Motors experience" width="1600" height="900" /></figure></section>
  <section id="experience" class="ui-section ui-showcase theme-dark variant-full-bleed"><div class="ui-container showcase-grid"><div><p class="eyebrow">The experience</p><h2>Crafted around a singular feeling.</h2><p class="lead">Current Motors brings its most important ideas forward and lets every supporting detail recede.</p><a class="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/tesla/tesla-composition.svg" alt="Original abstract composition representing the Current Motors experience" width="1600" height="900" loading="lazy" /></figure></div></section>
  <section id="craft" class="ui-section ui-showcase theme-light variant-light-stage"><div class="ui-container showcase-grid"><div><p class="eyebrow">The craft</p><h2>Material, light, and motion in balance.</h2><p class="lead">Purposeful materials, durable choices, and a precise visual rhythm make the experience feel complete without feeling crowded.</p><a class="text-link" href="#principles">Read the principles</a></div><div class="material-study" aria-hidden="true"><span></span><span></span><span></span></div></div></section>
  <section id="principles" class="ui-section ui-features theme-light variant-alternating"><div class="ui-container"><p class="eyebrow">Guiding principles</p><h2>What makes Current Motors feel different.</h2><p class="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div class="feature-grid"><article><span class="marker">01</span><h3>Sculpted proportion</h3><p>Current Motors presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><span class="marker">02</span><h3>Purposeful material</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><span class="marker">03</span><h3>Measured performance</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
  <section id="proof" class="ui-section ui-metrics theme-dark variant-inline"><div class="ui-container"><p class="eyebrow">Measured in practice</p><h2>Current Motors, by the numbers.</h2><dl class="metrics-grid"><div><dt>less wasted effort</dt><dd>42%</dd></div><div><dt>customer delight</dt><dd>8.7/10</dd></div><div><dt>ready when needed</dt><dd>24/7</dd></div></dl></div></section>
  <section id="begin" class="ui-section ui-cta theme-dark variant-centered"><div class="ui-container cta-inner"><p class="eyebrow">The next step</p><h2>Experience the work in its purest form.</h2><p class="lead">Discover how Current Motors can turn a clear idea into an experience people remember.</p><a class="button primary" href="#top">Discover the collection</a></div></section>
  </main>
  <footer id="footer" class="ui-section ui-footer theme-light variant-minimal"><div class="ui-container footer-grid"><div><a class="brand" href="#top">Current Motors</a><p>A clean-sheet vehicle shaped around range, simplicity, and the pleasure of instant response.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p class="ui-container legal">© 2026 Current Motors. An original Praxis Flow demonstration brand.</p></footer>
</template>
