<script setup lang="ts">
</script>

<template>
  <a class="skip-link" href="#main">Skip to content</a>
  <header id="top" class="ui-section ui-navigation theme-light variant-editorial"><div class="ui-container nav-inner"><a class="brand" href="#top">Orbit Pay</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a class="button primary compact" href="#begin">Explore the story</a></div></header>
  <main id="main">
  <section id="overview" class="ui-section ui-hero theme-light variant-split-editorial"><div class="ui-container hero-copy"><p class="eyebrow">Orbit Pay</p><h1>A world of moments, moving freely.</h1><p class="lead">Human-centered payment experiences that connect everyday choices with global possibility.</p><div class="actions"><a class="button primary" href="#experience">Explore the story</a><a class="button secondary" href="#principles">See the story</a></div></div><figure class="hero-visual"><img src="/ui/mastercard/mastercard-composition.svg" alt="Original abstract composition representing the Orbit Pay experience" width="1600" height="900" /></figure></section>
  <section id="experience" class="ui-section ui-showcase theme-light variant-split"><div class="ui-container showcase-grid"><div><p class="eyebrow">The experience</p><h2>Every detail supports the story.</h2><p class="lead">Orbit Pay brings its most important ideas forward and lets every supporting detail recede.</p><a class="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/mastercard/mastercard-composition.svg" alt="Original abstract composition representing the Orbit Pay experience" width="1600" height="900" loading="lazy" /></figure></div></section>
  <section id="principles" class="ui-section ui-features theme-light variant-alternating"><div class="ui-container"><p class="eyebrow">Guiding principles</p><h2>What makes Orbit Pay feel different.</h2><p class="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div class="feature-grid"><article><span class="marker">01</span><h3>Clear from the start</h3><p>Orbit Pay presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><span class="marker">02</span><h3>Human at every scale</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><span class="marker">03</span><h3>Made to endure</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
  <section id="voices" class="ui-section ui-testimonials theme-light variant-editorial"><div class="ui-container"><h2>What people notice about Orbit Pay.</h2><div class="quote-grid"><figure><blockquote>The experience feels considered from the first moment, but never asks us to learn its logic.</blockquote><figcaption>Mara Chen · Design lead</figcaption></figure><figure><blockquote>We moved faster without sacrificing the quality or clarity our customers expect.</blockquote><figcaption>Jon Bell · Product director</figcaption></figure><figure><blockquote>It gives the team enough structure to stay aligned and enough room to do original work.</blockquote><figcaption>Amara Okafor · Studio founder</figcaption></figure></div></div></section>
  <section id="craft" class="ui-section ui-showcase theme-light variant-light-stage"><div class="ui-container showcase-grid"><div><p class="eyebrow">The craft</p><h2>Designed for the moments between milestones.</h2><p class="lead">Purposeful materials, durable choices, and a precise visual rhythm make the experience feel complete without feeling crowded.</p><a class="text-link" href="#principles">Read the principles</a></div><div class="material-study" aria-hidden="true"><span></span><span></span><span></span></div></div></section>
  <section id="begin" class="ui-section ui-cta theme-light variant-split"><div class="ui-container cta-inner"><p class="eyebrow">The next step</p><h2>Begin with a more thoughtful experience.</h2><p class="lead">Discover how Orbit Pay can turn a clear idea into an experience people remember.</p><a class="button primary" href="#top">Explore the story</a></div></section>
  </main>
  <footer id="footer" class="ui-section ui-footer theme-light variant-minimal"><div class="ui-container footer-grid"><div><a class="brand" href="#top">Orbit Pay</a><p>Human-centered payment experiences that connect everyday choices with global possibility.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p class="ui-container legal">© 2026 Orbit Pay. An original Praxis Flow demonstration brand.</p></footer>
</template>
