<script setup lang="ts">
</script>

<template>
  <a class="skip-link" href="#main">Skip to content</a>
  <header id="top" class="ui-section ui-navigation theme-dark variant-global"><div class="ui-container nav-inner"><a class="brand" href="#top">Tempo</a><nav aria-label="Primary"><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li><li><a href="#principles">Principles</a></li></ul></nav><a class="button primary compact" href="#begin">Start building</a></div></header>
  <main id="main">
  <section id="overview" class="ui-section ui-hero theme-light variant-centered-product"><div class="ui-container hero-copy"><p class="eyebrow">Tempo</p><h1>Time that feels like yours.</h1><p class="lead">A calmer way to shape meetings, protect focus, and keep a team in step.</p><div class="actions"><a class="button primary" href="#experience">Start building</a><a class="button secondary" href="#principles">See the story</a></div></div><figure class="hero-visual"><img src="/ui/cal/cal-composition.svg" alt="Original abstract composition representing the Tempo experience" width="1600" height="900" /></figure></section>
  <section id="proof" class="ui-section ui-metrics theme-dark variant-grid"><div class="ui-container"><p class="eyebrow">Measured in practice</p><h2>Tempo, by the numbers.</h2><dl class="metrics-grid"><div><dt>typical response</dt><dd>18 ms</dd></div><div><dt>service availability</dt><dd>99.99%</dd></div><div><dt>faster iteration</dt><dd>3×</dd></div></dl></div></section>
  <section id="principles" class="ui-section ui-features theme-light variant-grid"><div class="ui-container"><p class="eyebrow">Guiding principles</p><h2>What makes Tempo feel different.</h2><p class="lead section-intro">A small set of strong decisions creates a recognizable experience across every screen and every moment.</p><div class="feature-grid"><article><span class="marker">01</span><h3>Observable by default</h3><p>Tempo presents the next useful action clearly, with nothing unnecessary competing for attention.</p></article><article><span class="marker">02</span><h3>Fast under pressure</h3><p>Flexible foundations adapt to real work while keeping the experience coherent and recognizable.</p></article><article><span class="marker">03</span><h3>Open at the edges</h3><p>Small interactions, responsive pacing, and accessible defaults make quality visible in everyday use.</p></article></div></div></section>
  <section id="experience" class="ui-section ui-showcase theme-light variant-split"><div class="ui-container showcase-grid"><div><p class="eyebrow">The experience</p><h2>Clarity at every layer.</h2><p class="lead">Tempo brings its most important ideas forward and lets every supporting detail recede.</p><a class="text-link" href="#principles">Explore the details</a></div><figure><img src="/ui/cal/cal-composition.svg" alt="Original abstract composition representing the Tempo experience" width="1600" height="900" loading="lazy" /></figure></div></section>
  <section id="community" class="ui-section ui-logo-cloud theme-light variant-row"><div class="ui-container"><h2>Trusted by teams building with Tempo.</h2><ul class="logo-row"><li>Northstar</li><li>Common Ground</li><li>Bright Labs</li><li>Open Field</li><li>New Arc</li><li>Good Work</li></ul></div></section>
  <section id="begin" class="ui-section ui-cta theme-light variant-band"><div class="ui-container cta-inner"><p class="eyebrow">The next step</p><h2>Put clarity into production.</h2><p class="lead">Discover how Tempo can turn a clear idea into an experience people remember.</p><a class="button primary" href="#top">Start building</a></div></section>
  </main>
  <footer id="footer" class="ui-section ui-footer theme-light variant-columns"><div class="ui-container footer-grid"><div><a class="brand" href="#top">Tempo</a><p>A calmer way to shape meetings, protect focus, and keep a team in step.</p></div><div><h2>Explore</h2><ul><li><a href="#overview">Overview</a></li><li><a href="#experience">Experience</a></li></ul></div><div><h2>Company</h2><ul><li><a href="#principles">Principles</a></li><li><a href="#begin">Contact</a></li></ul></div></div><p class="ui-container legal">© 2026 Tempo. An original Praxis Flow demonstration brand.</p></footer>
</template>
