apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DJANGO_SETTINGS_MODULE: config.settings.production
  ALLOWED_HOSTS: api,{{projectName}}
  DATABASE_HOST: postgres
  DATABASE_NAME: app
  DATABASE_USER: app
  DATABASE_PORT: "5432"
  LOG_LEVEL: INFO
