import "./globals.css";

export const metadata = { title: "{{projectName}}", description: "Generated by Praxis Flow" };

export default function RootLayout({ children }) {
  return <html lang="en"><body>{children}</body></html>;
}
