input { beats { port => 5044 } }
filter {
  if [message] =~ /^\s*\{/ {
    json { source => "message" skip_on_invalid_json => true }
  }
}
output {
  elasticsearch {
    hosts => ["http://logs-elasticsearch:9200"]
    index => "praxis-%{+YYYY.MM.dd}"
  }
}
